### ISSUE TITLE
Sending report to TestRail failed TypeError: Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by moonvi** [DamianOsipiuk/testcafe-reporter-testrail#15]
I've met with the mapping problem when sending tests results to existing run using env.TESTRAIL_RUN_ID
Previous runs have been passed successfully to TestRail but starts failing when I added new parameters to TeamCity:
- env.TESTRAIL_RUN_ID
- env.TESTRAIL_UPDATE_RUN_TEST_CASES
- env.TESTRAIL_UPLOAD_SCREENSHOTS

Full configuration:

Name	| Value passed to build
------------ | -------------
env.TESTRAIL_API_KEY	| ******
env.TESTRAIL_ENABLED |	true  
env.TESTRAIL_HOST	| ******
env.TESTRAIL_PROJECT_ID	| P1
env.TESTRAIL_RUN_ID	| R194  
env.TESTRAIL_RUN_NAME	| Web E2E Tests
env.TESTRAIL_SUITE_ID	| S57  
env.TESTRAIL_UPDATE_RUN_TEST_CASES	| false
env.TESTRAIL_UPLOAD_SCREENSHOTS	| true
env.TESTRAIL_USER	| ******

So the results not posted to TestRail and gives an **error**:

[12:55:11][TestRail] Sending report to TestRail failed TypeError: Cannot read property 'replace' of null
[12:55:11]    at prepareRun (...\testcafe\node_modules\testcafe-reporter-testrail\lib\index.js:90:50)
[12:55:11]    at runMicrotasks (<anonymous>)
[12:55:11]    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[12:55:11]    at ReporterPluginHost.TestcafeTestrailReporter.reportTaskDone (...\testcafe\node_modules\testcafe-reporter-testrail\lib\index.js:204:35)
[12:55:11]    at Reporter.dispatchToPlugin (...\testcafe\node_modules\testcafe\src\reporter\index.js:199:13)
[12:55:11]    at Reporter._onceTaskDoneHandler (...\testcafe\node_modules\testcafe\src\reporter\index.js:326:9)
[12:55:11]    at ...\testcafe\node_modules\testcafe\src\reporter\index.js:352:39
[12:55:11]    at async Promise.all (index 1)
[12:55:11]npm ERR! code ELIFECYCLE
[12:55:11]npm ERR! errno 1
[12:55:11]npm ERR! Exit status 1

_NOTE:_
Due to confidential info I replaced some data in env params to ******, and to ... in error details.
testcafe: 1.10.0-rc.1
testcafe-reporter-testrail: 0.6.2

**TestRail has the following hierarchy:**
- Test Plan R193 with name = TeamCity updates and contains 2 runs:
 -- Test Run R194 with name = Smoke (contains tests from Suite S57 in Project P1)
 -- Test Run R195 with name = Basic Regression (contains tests from Suite S1 in Project P1)

I note that runs cannot be edited inside test plans even my user has all admin write/edit permissions. But the same issue when just 1 run created when run can be edited.

Could you please help with that?

**Comment by DamianOsipiuk** [comment]
@moonvi Hello and thanks for the report.

The first issue with the description being null is indeed not being handled gracefully. I will provide a fix for that shortly so it would not be na issue in the future.

As for the second issue, it is not supported currently, as there is an different endpoint to update test runs that are part of test plans. It will require additional `TESTRAIL_PLAN_ID` configuration entry.

Until support for this will be added you can use test runs that are outside of test plans.

**Comment by moonvi** [comment]
@DamianOsipiuk Thank you!

About 2nd issue: sure, it's okay to use separate run for me now but would be nice to have `TESTRAIL_PLAN_ID` in future.

Many thanks

**Comment by moonvi** [comment]
Hi @DamianOsipiuk 
Did you have a chance to look at the 1st issue with `null` ?

**Comment by moonvi** [comment]
@DamianOsipiuk Many thanks!

**Comment by moonvi** [comment]
> @moonvi Hi, I've released version 0.6.3 which should solve your issue with null description.
> 
> As for the plans support, i'm still waiting for TestRail team answer about API endpoint that is not working as intended.

Hi, @DamianOsipiuk 
The issue with null description is resolved - results have been passed to TestRail _but_ `undefined` is added to the Test Run without description.
